apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: quran
  labels:
    app: admin-service
spec:
  type: ClusterIP
  ports:
  - port: 3008
    targetPort: 3008
    protocol: TCP
    name: http
  selector:
    app: admin-service
