apiVersion: v1
kind: Service
metadata:
  name: quran-service
  namespace: quran
  labels:
    app: quran-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: quran-service
